name: Update ICS daily
on:
  schedule:
    # Körs 00:00, 10:00 och 14:00 UTC
    # 01:00, 11:00, 15:00 svensk tid vinter
    # 02:00, 12:00, 16:00 svensk tid sommar
    - cron: "0 0 * * *"
    - cron: "0 10 * * *"
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (Python + Playwright)
        run: |
          pip install playwright ics dateparser pytz google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib
          python -m playwright install --with-deps chromium

      - name: Build ICS
        run: HEADLESS=true python notion_calendar_full.py

      - name: Write service account key to file
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > sa.json

      - name: Upload ICS to Google Drive (same file ID)
        run: |
          python - <<'PY'
          from google.oauth2 import service_account
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload

          FILE_ID = "18aBgZxvzgxWifeSju4z0_Q7IeTvs01rC"
          FILE_PATH = "notion_calendar.ics"

          creds = service_account.Credentials.from_service_account_file(
              "sa.json",
              scopes=['https://www.googleapis.com/auth/drive']
          )
          service = build('drive', 'v3', credentials=creds)
          media = MediaFileUpload(FILE_PATH, mimetype='text/calendar', resumable=False)
          service.files().update(fileId=FILE_ID, media_body=media).execute()
          print("Drive file updated:", FILE_ID)
          PY
